### ISSUE TITLE
General Questions about the Dataset

### ISSUE THREAD

**Issue by alibrahimzada** [BugSwarm/bugswarm#38]
Hello, I have the following questions about the dataset. It would be great if you could answer them. Thanks.

- For a specific pair, the number of tests executed in the passing job have increased w.r.t failing job. Do these newly added tests correspond to the fixed version of the code? If yes, why they were not executed on the buggy version? For instance, please consider the pair instance with image tag `square-okhttp-99350732`. The failed job has `num_tests_run` as `1582`, while for the passing job it has increased to `1877`.
- Currently about ~50% of pairs in Java do not have the name(s) of the failing tests. The documentation says that this attribute is not reliable at this time. Is there any improvements in this part? Can we get the names of the failing tests which are currently missing?

**Comment by ryanajae** [comment]
The `num_tests_run` attribute is extracted from the Travis-CI historical logs of each triggered build. The tests to be run are determined by the repo owners, who may enable or disable tests at will. For example, developers can add new tests after fixing a bug. 

Many of the artifacts’ failed builds may originally fail due to a variety of errors in addition to test failures (e.g., dependency errors). The `num_tests_run` for these cases is `0` because no tests are run. Furthermore, the ‘failed_tests’ attribute in these cases should be empty. About 50% of the failed builds in BugSwarm are due to failed tests. Failed test information in the database is reliable at this time.

Note that the artifact that you describe, `square-okhttp-99350732`, is labeled as “flaky” in our dataset. This means that the historical log is not matched consistently by the build scripts. To get non-flaky artifacts, you can use filters in our [API](http://www.bugswarm.org/docs/toolset/bugswarm-rest-api/):

```
api_filter = '{"reproduce_successes":5, "lang":"Java"}'
```

Please let us know if you have any further questions!

**Comment by alibrahimzada** [comment]
Thank you very much for your response. I will close this issue, and reopen in future if necessary.
